all:
  children:
    web:
      hosts:
        192.168.123.11:
          ansible_user: tanvir1
          ansible_password: "{{ ansible_password_tanvir1 }}"
          ansible_become: yes
          ansible_become_method: sudo
          ansible_become_password: "{{ ansible_password_tanvir1 }}"

        192.168.123.12:
          ansible_user: tanvir2
          ansible_password: "{{ ansible_password_tanvir2 }}"
          ansible_become: yes
          ansible_become_method: sudo
          ansible_become_password: "{{ ansible_password_tanvir2 }}"

        192.168.123.13:
          ansible_user: tanvir3
          ansible_password: "{{ ansible_password_tanvir3 }}"
          ansible_become: yes
          ansible_become_method: sudo
          ansible_become_password: "{{ ansible_password_tanvir3 }}"

    nginx:
      hosts:
        192.168.123.10:
          ansible_user: nginx
          ansible_password: "{{ ansible_password_nginx }}"
          ansible_become: yes
          ansible_become_method: sudo
          ansible_become_password: "{{ ansible_password_nginx }}"
