---
- name: update the cache
  apt:
    update_cache: yes

- name: Installed required packages (Nginx)
  apt:
    name:
      - nginx
      - curl
    state: present

- name: Configure Nginx reverse proxy
  copy:
    dest: /etc/nginx/sites-available/default
    content: |
      upstream backend_app {
          server 192.168.123.11:3000;
          server 192.168.123.12:3000;
          server 192.168.123.13:3000;
      }

      server {
          listen 80;

          location / {
              proxy_pass http://backend_app;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
          }
      }

- name: Test Nginx configuration
  command: nginx -t
  register: nginx_test
  failed_when: "'successful' not in nginx_test.stderr"
  ignore_errors: yes

- name: Restart Nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes
