- name: Start Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Create Nginx reverse proxy config
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /tmp/nginx.conf
  vars:
    backend_servers: "{{ backend_servers }}"

- name: Pull Nginx Docker image
  community.docker.docker_image:
    name: "{{ nginx_image }}"
    source: pull

- name: Run Nginx container with custom config
  community.docker.docker_container:
    name: "{{ nginx_container_name }}"
    image: "{{ nginx_image }}"
    state: started
    restart_policy: always
    ports:
      - "80:80"
    volumes:
      - /tmp/nginx.conf:/etc/nginx/conf.d/default.conf:ro
