name: CD - Install Apps on Runner VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Ansible Playbook
        run: |
          cd ./ansible && ansible -i inventory/Hosts.yml web -m ping
