name: CD Testing Access

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible if missing
        run: |
          if ! command -v ansible &> /dev/null
          then
            sudo apt update && sudo apt install -y ansible
          fi

      - name: Run Ansible playbook
        working-directory: ./ansible
        run: |
          ansible-playbook -i inventory.ini print_hello.yml
