name: CD Print Hello

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print hello in VM console
        run: |
          set -x
          echo "Hello from the VM!"
          sudo apt update
          date
