name: CD - setting starting servers in vms
on:
  workflow_run:
    workflows: ["CI - Build & Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    strategy:
      matrix:
        vm: [VM1, VM2, VM3]

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to VM1
        if: matrix.vm == 'VM1'
        uses: ./actions/deploy/
        with:
          vm-ip: ${{ secrets.VM1_IP }}
          vm-user: ${{ secrets.VM1_USER }}
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VM2
        if: matrix.vm == 'VM2'
        uses: ./actions/deploy/
        with:
          vm-ip: ${{ secrets.VM2_IP }}
          vm-user: ${{ secrets.VM2_USER }}
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VM3
        if: matrix.vm == 'VM3'
        uses: ./actions/deploy/
        with:
          vm-ip: ${{ secrets.VM3_IP }}
          vm-user: ${{ secrets.VM3_USER }}
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
