name: CD - Install Apps on Runner VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Ansible Playbook
        run: |
          cd ./ansible && ansible-playbook playbooks/site.yml
