name: CD Testing Access

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible if missing
        run: |
          set -x
          echo "Checking if Ansible is installed..."
          if ! command -v ansible &> /dev/null
          then
            echo "Ansible not found — installing..."
            date
            sudo apt update -y
            sudo apt install -y ansible
            date
          else
            echo "Ansible is already installed."
            ansible --version
          fi

      - name: Run Ansible playbook
        working-directory: ./ansible
        run: |
          set -x
          echo "Running Ansible playbook..."
          date
          ansible-playbook -i inventory.ini print_hello.yml -vvv
          date
